[package]
authors = ["Warren Alphonso <warrenalphonso02@gmail.com>"]
edition = "2018"
name = "bevy_chess"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
bevy_mod_picking = "0.3.1"
